# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "..", "/jimhttp"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "384"]
    # vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
  end

  config.vm.define "jimhttpdev", autostart: false do |jimhttpdev|
    jimhttpdev.vm.box = "ubuntu/trusty64"
    jimhttpdev.vm.network "forwarded_port", guest: 8080, host: 8080
  end
end
